version: '3'

services:
  ollama-proxy:
    build: .
    container_name: ollama-proxy
    ports:
      - "8765:8765"
    restart: unless-stopped
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge